services:
  redis:
    image: redis:8.8-alpine
    container_name: redis_auth
    command: redis-server --requirepass redis-auth-pass --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      start_period: 10s
    networks:
      - redis-network

  auth-svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_svc
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis-network
    ports:
      - "9606:8080"

networks:
  redis-network:
